### PR TITLE
[#42][Integrate] As a logged-in user, when I press on the notification banner it will open the Github website with my default browser

### PR DESCRIPTION
**Pull request by markgravity**
#42

## What happened 👀

Integrate open a link when tapping on a notification
 
## Insight 📝

Store URL in `UNMutableNotificationContent.userInfo` and handle to open the link in `UNUserNotificationCenterDelegate`
 
## Proof Of Work 📹

https://user-images.githubusercontent.com/17875522/134448593-88579039-fa03-484b-81fa-f295ba019b40.mov

### CODE REVIEW

**Review by blyscuit — APPROVED** [review]
Looks good

**Review by llleyelll — COMMENTED** [review]
If the app is open on a different desktop from the browser when tapping on the notification banner it will show the app first (and also open the link)
Should we prevent the notification banner from open the app?

Example:

https://user-images.githubusercontent.com/45258998/134453843-3acc0d7b-409a-4a87-8733-183625a81b72.mov

**Comment by blyscuit** [comment]
> If the app is open on a different desktop from the browser when tapping on the notification banner it will show the app first (and also open the link)
> Should we prevent the notification banner from open the app?
> 
> Example:
> 
>  Screen.Recording.2021-09-23.at.11.16.13.AM.mov

Is there a way to prevent that?

**Comment by llleyelll** [comment]
> > If the app is open on a different desktop from the browser when tapping on the notification banner it will show the app first (and also open the link)
> > Should we prevent the notification banner from open the app?
> > Example:
> > Screen.Recording.2021-09-23.at.11.16.13.AM.mov
> 
> Is there a way to prevent that?

I try to search for a way to do that but don't find any. Seems like the only way is to close the window. 😓

**Review by llleyelll — APPROVED** [review]

**Pull request merged**
